/*-------------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported from C# to Java by Wolfgang Ahorner
with improvements by Pat Terry, Rhodes University
ported to Typescript by Stefan Kempinger, Univ. of Linz

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than
Coco/R itself) does not fall under the GNU General Public License.
------------------------------------------------------------------------*/

import * as fs from "fs";
import * as path from "path";

export class Trace {
    file: string;              /* pdt */
    w: number;

    private CheckOpen() {
        if (this.w == undefined) {
            try {
                this.w = fs.openSync(this.file,"w") /* pdt */
            } catch (e) {
                throw new Error("Could not open " + this.file);
            }
        }
    }

    constructor(dir: string) {
        this.file = path.join(dir, "trace.txt"); /* pdt */
    }

// returns a string with a minimum length of |w| characters
// the string is left-adjusted if w < 0 and right-adjusted otherwise
    public formatString(s: string, w: number): string {
        let size = s.length;
        let b = "";
        if (w >= 0) {
            for (let i = 0; i < w - size; i++) b += " ";
            return (b.toString() + s);
        } else {
            for (let i = w; i < -size; i++) b += " ";
            return (s + b.toString());
        }
    }


    // writes a string with a minimum length of |w| characters
    public Write(s: string, w?: number) {
        if (w != undefined) {
            s = this.formatString(s, w)
        }
        this.CheckOpen();
        fs.writeSync(this.w, s);
    }

    public WriteLine(s?: string, w?: number) {
        this.CheckOpen();
        if (s == undefined) {
            fs.writeSync(this.w,"\n");
        } else {
            if (w != undefined)
                s = this.formatString(s, w)
            fs.writeSync(this.w,s+"\n");
        }
    }

    public Close() { /* pdt */
        if (this.w != undefined) {
            // this.w.close();
            fs.close(this.w,function () {})
            console.log("trace output is in " + this.file);
        }
    }

}